version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-dependencies:
        patterns:
          - "actions*"
      compairifuel-dependencies:
        applies-to: version-updates
        patterns:
          - "compairifuel*"
      compairifuel-security-dependencies:
        applies-to: security-updates
        patterns:
          - "compairifuel*"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "actions*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]